routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/**
 * Testing Purposes
 */
Route::group(['prefix' => 'test'], function () {
	Route::get('future-bookings', ['uses' => 'TestController@fetchFutureBookings']);

	Route::get('updated-prices', ['uses' => 'TestController@showUpdatedPrices']);

	Route::get('show-add-on-check-fields', ['uses' => 'TestController@showAddOnsCheckOutFields']);

	Route::post('create-add-on-check-fields', ['uses' => 'TestController@createAddOnsCheckOutFields']);
});

/**
 * UPGRADES
 */
Route::group(['prefix' => 'upgrade', 'namespace' => 'Util'], function () {
});

/**
 * Display metrics
 */
Route::group(['prefix' => 'metrics/data', 'namespace' => 'Util'], function () {
	Route::get('/', [
		'uses' => 'MetricsDisplayController@showMetricsData',
		'as'   => 'metrics.data'
	]);

	Route::post('/new-tickets/', [
		'uses' => 'MetricsDisplayController@showMetricsNewTicketsData',
		'as'   => 'metrics.data.new.tickets'
	]);

	Route::post('/followups/', [
		'uses' => 'MetricsDisplayController@showMetricsFollowupsData',
		'as'   => 'metrics.data.followups'
	]);

	Route::post('/in-progress/', [
		'uses' => 'MetricsDisplayController@showMetricsInProgressData',
		'as'   => 'metrics.data.inprogress'
	]);
});

/**
 * Temp Route
 */
Route::get('audit/download', ['uses' => 'Settlement\PaymentSettlementController@downloadReport']);

/**
 * WATERMARK
 */
Route::get('images/watermark', ['uses' => 'App\AppController@watermarkImage']);

/**
 * AUTHENTICATION
 */
Route::group(['namespace' => 'App'], function () {
	Route::post('login', 'LoginController@postLogin');

	Route::get('/', [
		'middleware' => 'auth',
		'uses'       => 'AppController@authenticate'
	]);

	Route::get('login', [
		'as'         => 'login',
		'middleware' => 'guest.custom',
		'uses'       => 'AppController@showLogin'
	]);

	Route::any('logout', [
		'as'         => 'logout',
		'middleware' => 'auth',
		'uses'       => 'AppController@doLogout'
	]);
});

/**
 * RESTRICTED ACCESS
 */
Route::group(['middleware' => 'auth', 'prefix' => '/'], function () {
	/**
	 * Change Password
	 */
	Route::group(['prefix' => 'change-password', 'namespace' => 'App'], function () {
		Route::get('/', ['uses' => 'ChangePasswordController@showChangeScreen']);
		Route::post('/', ['uses' => 'ChangePasswordController@updatePassword']);
	});

	/**
	 * Syrow access
	 */
	Route::group(['prefix'    => 's',
	              'namespace' => 'Util',
	              'as'        => "syrow."], function () {
		Route::get('/tickets/list', [
			'as'   => 'tickets.list',
			'uses' => 'SyrowDashBoardController@showTicketList'
		]);

		Route::post('/tickets/list/data', [
			'as'   => 'tickets.list.data',
			'uses' => 'SyrowDashBoardController@getTicketData'
		]);

		Route::post('/ticket/save/invalid', [
			'as'   => 'ticket.save.invalid',
			'uses' => 'SyrowDashBoardController@saveInvalidTicket'
		]);

		Route::post('/ticket/save/comments/{ticketId}', [
			'as'   => 'ticket.save.comments',
			'uses' => 'SyrowDashBoardController@updateTicketComments'
		]);

		Route::post('/phone/save/comments/{phone}', [
			'as'   => 'phone.save.comments',
			'uses' => 'SyrowDashBoardController@updateTicketNotFoundComments'
		]);

		Route::post('/ticket/request/save/{ticketId}', [
			'as'   => 'ticket.request.save',
			'uses' => 'SyrowDashBoardController@saveRequest'
		]);
	});

	/**
	 * Pinterest Api's
	 */
	Route::group(['prefix' => 'pinterest', 'namespace' => 'Pinterest', 'as' => "pinterest."], function () {
		Route::get('/getCode', [
			'as'   => 'code',
			'uses' => 'PinterestController@getPinterestCode'
		]);

		Route::get('/getAccessToken', [
			'as'   => 'token',
			'uses' => 'PinterestController@getPinterestAccessToken'
		]);

		Route::get('/connect', [
			'as'   => 'connect',
			'uses' => 'PinterestController@pinterestOAuth'
		]);

		Route::get('/callback', [
			'as'   => 'connect',
			'uses' => 'PinterestController@callbackFromPinterest'
		]);

		Route::get('/profile', [
			'as'   => 'profile.info',
			'uses' => 'PinterestController@getProfileInfo'
		]);

		Route::post('/tickets/list/data', [
			'as'   => 'tickets.list.data',
			'uses' => 'SyrowDashBoardController@getTicketData'
		]);
	});

	/**
	 * Sales dashboard
	 */
	Route::group(['prefix'    => 'sales',
	              'namespace' => 'Util',
	              'as'        => "sales."], function () {
		Route::get('/dashboard/{ticketRange?}', [
			'as'   => 'tickets.list',
			'uses' => 'SalesDashBoardController@showTicketList'
		]);

		Route::post('/tickets/list/data', [
			'as'   => 'tickets.list.data',
			'uses' => 'SalesDashBoardController@getTicketData'
		]);

		Route::post('/tickets/search/data', [
			'as'   => 'tickets.search.data',
			'uses' => 'SalesDashBoardController@showTicketList'
		]);

		Route::post('/tickets/admin/data', [
			'as'   => 'tickets.search.data',
			'uses' => 'SalesDashBoardController@showAdminMetricsData'
		]);

		Route::post('/ticket/save/invalid', [
			'as'   => 'ticket.save.invalid',
			'uses' => 'SalesDashBoardController@saveInvalidTicket'
		]);

		Route::post('/ticket/save/comments/{ticketId}', [
			'as'   => 'ticket.save.comments',
			'uses' => 'SalesDashBoardController@updateTicketComments'
		]);

		Route::post('/phone/save/comments/{phone}', [
			'as'   => 'phone.save.comments',
			'uses' => 'SalesDashBoardController@updateTicketNotFoundComments'
		]);

		Route::post('/ticket/request/save/{ticketId}', [
			'as'   => 'ticket.request.save',
			'uses' => 'SalesDashBoardController@saveRequest'
		]);
	});

	/**
	 * Add new location
	 */
	Route::post('add-area', ['uses' => 'App\AppController@addNewArea']);

	/**
	 * Update selling status
	 */
	Route::group(['prefix'    => 'update-selling-status/{productTypeId}/{productId}/{statusId?}',
	              'namespace' => 'Util',
	              'as'        => "selling.status."], function () {
		Route::post('/', [
			'as'   => 'update',
			'uses' => 'UtilitiesController@updateSellingStatus'
		]);
	});

	/**
	 * Copy feature
	 */
	Route::group(['prefix' => 'copy', 'namespace' => 'Util'], function () {
		Route::get('/', [
			'as'   => 'show.copy.model',
			'uses' => 'CopyOptionController@showCopyModel'
		]);

		Route::post('/', [
			'as'   => 'copy.model.save',
			'uses' => 'CopyOptionController@saveCopyModel'
		]);
	});

	/*
	 * Tracking the order, call to customer, call to partner, customer feedback after party
	 */
	Route::group(['middleware' => 'authorize.tracking',
	              'prefix'     => 'tracking',
	              'as'         => 'tracking.'], function () {
		Route::group(['namespace' => 'Util'], function () {

			Route::get('pending/feedback', [
				'as'   => 'pending.feedback',
				'uses' => 'CustomerFeedbackController@showPendingFeedback'
			]);

			Route::get('pending/feedback/approval', [
				'as'   => 'pending.feedback.approval',
				'uses' => 'CustomerFeedbackController@showPendingApproval'
			]);
		});

		Route::group(['namespace' => 'Tracking'], function () {

			Route::get('/party/current', [
				'as'   => 'list',
				'uses' => 'TrackingController@showList'
			]);

			Route::get('/party/all/{done?}', [
				'as'   => 'party.all',
				'uses' => 'TrackingController@showList'
			]);

			Route::get('{bookingId}/{tracker_id}', [
				'as'   => 'show.model',
				'uses' => 'TrackingController@showModel'
			]);

			Route::post('details/save', [
				'as'   => 'save',
				'uses' => 'TrackingController@saveModel'
			]);

			Route::post('patner/unavailable', [
				'as'   => 'partner.unavailable',
				'uses' => 'TrackingController@sendPartnerUnavailableMail'
			]);
		});
	});

	/**
	 * Dash board based on each team.
	 */
	Route::group(['prefix'    => 'dash-board',
	              'as'        => 'dashBoard.',
	              'namespace' => 'DashBoard'], function () {
		Route::get('/', [
			'as'   => 'list',
			'uses' => 'DashBoardController@showList'
		]);
	});

	/**
	 * CRM Dash board based on ticket data.
	 */
	Route::group(['prefix'     => 'crm-analytics',
	              'as'         => 'crmDashBoard.',
	              'middleware' => 'authorize.old-dashboard',
	              'namespace'  => 'DashBoard'], function () {
		Route::get('/new-tickets', [
			'as'   => 'new.tickets.list',
			'uses' => 'CrmDashBoardController@showNewTickets'
		]);

		Route::get('/progress-tickets', [
			'as'   => 'progress.tickets.list',
			'uses' => 'CrmDashBoardController@showInProgressTickets'
		]);

		Route::get('/return-tickets', [
			'as'   => 'return.tickets.list',
			'uses' => 'CrmDashBoardController@showReturnTickets'
		]);

		Route::get('/missed-tickets', [
			'as'   => 'missed.tickets.list',
			'uses' => 'CrmDashBoardController@showMissedTickets'
		]);

		Route::get('/prospect-tickets', [
			'as'   => 'prospect.tickets.list',
			'uses' => 'CrmDashBoardController@showProspectTickets'
		]);

		Route::post('/return-tickets/{ticketId}', [
			'as'   => 'return.tickets.updates',
			'uses' => 'CrmDashBoardController@showReturnTicketUpdates'
		]);

		Route::post('/history/{ticketId}', [
			'as'   => 'history.tickets.updates',
			'uses' => 'CrmDashBoardController@showHistoryUpdates'
		]);

		Route::get('/avail-checks', [
			'as'   => 'avail-check.list',
			'uses' => 'CrmDashBoardController@showAvailChecks'
		]);

		Route::get('/metrics', [
			'as'   => 'metrics',
			'uses' => 'CrmDashBoardController@showMetrics'
		]);

		Route::get('/history', [
			'as'   => 'history',
			'uses' => 'CrmDashBoardController@showHistory'
		]);
	});
	/**
	 * ops-dashbaord based on ticket data
	 */
	Route::group(['prefix'    => 'ops-dashboard',
	              'as'        => 'ops-dashboard.',
	              'namespace' => 'DashBoard'], function () {
		Route::get('/', [
			'as'   => 'home',
			'uses' => 'OpsDashboardController@showOrderConfirmationTickets'
		]);

		Route::get('tabs-count', [
			'as'   => 'tabs-count',
			'uses' => 'OpsDashboardController@fetchTabsCount'
		]);

		Route::group(['prefix' => 'order-confirmation-tickets',
		              'as'     => 'order-confirmation-tickets.'], function () {

app/Http/Controllers/DashBoard/PiabDashboardController.php
<?php

namespace App\Http\Controllers\DashBoard;

use App\Http\Controllers\Base\BaseController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

class PiabDashboardController extends BaseController
{

	public function showProductBookings()
	{
		$user = Auth::user();
		$accessToken = $this->getAccessTokenFromUserId($user);

		$options = [
			"url"         => config("evibe.api.base_url") . config("evibe.api.piab.dashboard.product-bookings.list"),
			"method"      => "GET",
			"accessToken" => $accessToken,
			"jsonData"    => request()->all()
		];

		$data = $this->makeGuzzleRequest($options);

		return view('dashboard.piab.product-bookings.list', ['data' => $data]);

	}
	public function showProductBookingInfo($productBookingId){
		$user = Auth::user();
		$accessToken = $this->getAccessTokenFromUserId($user);
		$options = [
			"url"         => config("evibe.api.base_url") . config("evibe.api.piab.dashboard.product-bookings.info"),
			"method"      => "GET",
			"accessToken" => $accessToken,
			"jsonData"    => [
				'productBookingId' => $productBookingId
			]
		];

		$data = $this->makeGuzzleRequest($options);

		return view('dashboard.piab.product-bookings.info', ['data' => $data]);
	}

	public function updateProductBookingStatus()
	{
		$user = Auth::user();
		$accessToken = $this->getAccessTokenFromUserId($user);
		$options = [
			"url"         => config("evibe.api.base_url") . config('evibe.api.piab.dashboard.product-bookings.update-status'),
			"method"      => "POST",
			"accessToken" => $accessToken,
			"jsonData"    => request()->all()
		];
		$data = $this->makeGuzzleRequest($options);

		return response()->json($data);

	}

}

resources/views/dashboard/crm-filters.blade.php
<div class="filter-group-options ls-none no-mar no-pad">
	<h4 class="in-blk pull-left">
		Filter Options
	</h4>
	<div class="in-blk filter-date-btn-wrap pad-t-3 pad-l-5">
		@if($data['filterReset'])
			<a class="btn btn-xs btn-warning" href="{{ route('crmDashBoard.new.tickets.list') }}">Reset</a>
		@endif
	</div>
	<div class="clearfix"></div>

	<div class="filter-group">

		<div class="text-center">
			<div class="filter-title pull-left">By Occasion</div>
			<select class="form-control" name="occasion" id="occasion">
				<option value="all">All Occasions</option>
				@foreach($data['typeEvents'] as $key => $event)
					<option value="{{$key}}"
							@if(request()->input('occasion')== $key)selected @endif>{{$event}}</option>
				@endforeach
			</select>
		</div>

		<div class="text-center pad-t-10">
			<div class="filter-title pull-left">By lead Status</div>
			<select class="form-control pad-t-8" name="lead-status" id="ticketLeadStatusForAnalytics">
				<option value="all">All Lead status</option>
				<option value="notSet"
						@if(request()->input('leadStatus')== "notSet") selected @endif>Not set
				</option>
				@foreach($data['typeLeadStatus'] as $key => $leadStatus)
					<option value="{{$key}}"
							@if(request()->input('leadStatus')== $key)selected @endif>{{$leadStatus}}</option>
				@endforeach
			</select>
		</div>

		<div class="text-center pad-t-10">
			<div class="filter-title pull-left">By Ticket Status</div>
			<select class="form-control" name="ticket-status" id="ticketStatus">
				<option value="all">All Ticket status</option>
				@foreach($data['typeTicketStatus'] as $key => $typeTicketStatus)
					<option value="{{$key}}"
							@if(request()->input('ticketStatus')== $key)selected @endif>{{$typeTicketStatus}}</option>
				@endforeach
			</select>
		</div>

		<div class="text-center pad-t-10">
			<div class="filter-title pull-left">By handler</div>
			<select class="form-control" name="handler" id="handler">
				<option value="all">All Handlers</option>
				@foreach($data['handlerDetails'] as $key => $handlerDetail)
					<option value="{{$key}}"
							@if(request()->input('handler')== $key)selected @endif>{{$handlerDetail}}</option>
				@endforeach
			</select>
		</div>

		<div class="text-center pad-t-10">
			<div class="filter-title pull-left">By Created handler</div>
			<select class="form-control" name="createdByHandler" id="createdByHandler">
				<option value="all">All Handlers</option>
				@foreach($data['handlerDetails'] as $key => $handlerDetail)
					<option value="{{$key}}"
							@if(request()->input('createdByHandler')== $key)selected @endif>{{$handlerDetail}}</option>
				@endforeach
			</select>
		</div>


	</div>

</div>
<div class="text-muted pad-t-10 pad-b-10">
	<i class="glyphicon glyphicon-info-sign"></i> Difference of dates should not be more than 7 days
</div>

resources/views/dashboard/crm-history.blade.php
@extends('layout.base')

@section('content')
	<div class="panel panel-default page-content mar-l-10 mar-r-10">
		<div class="panel-body">
			<div class="title-sec no-pad">
				<div class="text-center">
					<div class="btn-group" role="group" aria-label="...">
						<a class="btn btn-default" href="{{route('crmDashBoard.list')}}">Summary</a>
						<a class="btn btn-default active" href="{{route('crmDashBoard.history')}}">History</a>
						<a class="btn btn-default hide" href="{{route('crmDashBoard.metrics')}}">Metrics</a>
					</div>
				</div>
				<div class="pull-left">
					<div class="font-20 pad-t-10">Showing history from {{$data['humanReadableStartDate']}} to {{$data['humanReadableEndDate']}}</div>
				</div>
				<div class="clearfix"></div>
				<div class="col-sm-2 col-md-2 col-xs-2 col-lg-2">

					<h4 class="in-blk pull-left pad-t-10">
						Filter Options
					</h4>
					<div class="in-blk filter-date-btn-wrap pad-t-10 pad-l-5">
						@if($data['filterReset'])
							<a class="btn btn-xs btn-warning" href="{{ route('crmDashBoard.history') }}">Reset</a>
						@endif
					</div>
					<div class="clearfix"></div>
					<div class="filter-group ls-none no-mar">

						<div>
							<div class="filter-title pull-left">Select Dates</div>
							<div class="text-center pad-t-10">
								<input type="text"
										class="form-control filter-anlytics-date filter-anlytics-creation-start-time text-center"
										id="startTime"
										value="{{date('d-m-Y H:i',$data['startDate'])}}">
							</div>
						</div>

						<div>
							<div class="text-center text-bold filter-title">To</div>
							<div class="text-center pad-b-10">
								<input type="text"
										class="form-control filter-anlytics-date filter-anlytics-creation-end-time text-center"
										value="{{date('d-m-Y H:i',$data['endDate'])}}" id="endTime">
							</div>
						</div>
						<div class="text-center pad-t-10 hide">
							<div class="filter-title pull-left">By Status</div>
							<select class="form-control" name="ticketStatusId" id="ticketStatusId">
								<option value="all">All</option>
								@foreach($data['typeTicketStatus'] as $key=>$value)
									<option value="{{$key}}"
											@if(request()->input('ticketStatusId')== $key)selected @endif>{{$value}}</option>
								@endforeach
							</select>
						</div>

						<div class="text-center pad-t-10 hide">
							<div class="filter-title pull-left">By handler</div>
							<select class="form-control" name="handlerId" id="handlerId">
								<option value="all">All Handlers</option>
								@foreach($data['crmAndAdminDetails'] as $key=>$value)
									<option value="{{$key}}"
											@if(request()->input('handlerId')== $key)selected @endif>{{$value}}</option>
								@endforeach
							</select>
						</div>

						<div class="text-center filter-date-btn-wrap">
							<a class="btn btn-xs btn-primary btn-filter-by-cd">
								<button class="btn btn-xs btn-primary">FILTER</button>
							</a>
						</div>
					</div>
					<div class="text-muted pad-t-3">
						<i class="glyphicon glyphicon-info-sign"></i>
						Difference of dates should not be more than a week
					</div>
				</div>
				<div class="col-sm-10 col-md-10 col-xs-10 col-lg-10 pad-t-10">
					@if($data['tickets'])
						<table class="table table-hover table-responsive table-bordered table-hover text text-center"
								id="crmDashhistoryTable">
							<thead class="text text-info text-center">
							<tr>
								<th>Ticket Details</th>
								<th>Last Updated At</th>
								<th>Status</th>
								<th>Handler</th>
								<th>Update Source</th>
								<th>Update Comment</th>
							</tr>
							</thead>
							<tbody>
							@foreach($data['tickets'] as $key => $ticket)
								@php
									$updateCount = 0; $totalUpdateCount = count($ticket);
									$keyForTicketDetails = array_search($key, array_column($data['ticketDetails'],'id'));
									$ticketDetails = $keyForTicketDetails ? $data['ticketDetails'][$keyForTicketDetails] : '';
								@endphp
								@if($ticketDetails)
									@foreach($ticket as $ticketUpdate)
										<tr>
											@php
												$typeTicketStatusName = isset($data['typeTicketStatus'][$ticketUpdate['status_id']])
												? $data['typeTicketStatus'][$ticketUpdate['status_id']] : '';
												$handlerName = isset($data['crmAndAdminDetails'][$ticketUpdate['ticket_updater']])
												?$data['crmAndAdminDetails'][$ticketUpdate['ticket_updater']]:'';
												$updateCount = $updateCount+1;
											@endphp
											@if($updateCount == 1)
												<td rowspan="{{ $totalUpdateCount }}">
													<div class="text text-center pad-t-10">
														<a href="/tickets/{{ $key }}/information" target="_blank">
															@if($ticketDetails["name"])
																<div>
																	<i class="glyphicon glyphicon-user"></i>
																	{{ $ticketDetails['name'] }}
																</div>
															@else
																Not Set
															@endif
														</a>
														<div class="pad-t-5">
															<i class="glyphicon glyphicon-time"></i>
															@if($ticketDetails['event_date'])
																{{date('j-M-y, g:i A',$ticketDetails['event_date'])}}
															@else
																---
															@endif
														</div>
														<div class="pad-t-5">
															<i class="glyphicon glyphicon-phone"></i>
															@if($ticketDetails['phone'])
																{{$ticketDetails['phone']}}
															@else
																---
															@endif
														</div>
														<div class="pad-t-5">
															<i class="glyphicon glyphicon-list"></i>
															@if($ticketDetails['status_id'])
																@if(isset($data['typeTicketStatus'][$ticketDetails['status_id']]))
																	{{ $data['typeTicketStatus'][$ticketDetails['status_id']] }}
																@else
																	---
																@endif
															@else
																Not Set
															@endif
														</div>
														<div class="pad-t-5">
															<i class="glyphicon glyphicon-eye-open"></i>
															@if($ticketDetails['handler_id'])
																@if(isset($data['crmAndAdminDetails'][$ticketDetails['handler_id']]))
																	@php
																		$fullNameOfHandler = explode(" ",$data['crmAndAdminDetails'][$ticketDetails['handler_id']]);
																	@endphp
																	{{$fullNameOfHandler[0]}}
																@else
																	Non CRM member
																@endif
															@else
																Not Set
															@endif
														</div>
													</div>
												</td>
											@endif
											<td>
												<span class="text-center">{{ date('j-M-y, g:i A',strtotime($ticketUpdate["updated_at"])) }}</span>
											</td>
											<td>
												{{ $typeTicketStatusName }}
											</td>
											<td>
												@if($handlerName)
													@php
														$fullNameOfHandler = explode(" ",$handlerName);
													@endphp
													{{ $fullNameOfHandler[0] }}
												@else
													{{'Auto'}}
												@endif</td>
											<td>
												@if($ticketUpdate["type_update"])
													{{ $ticketUpdate["type_update"] }}
												@else
													{{'---'}}
												@endif</td>
											<td>
												<div class="text-left">
													@if($ticketUpdate["comments"])
														{!! $ticketUpdate["comments"] !!}
													@else
														{{'---'}}
													@endif
												</div>
											</td>
										</tr>
									@endforeach
								@endif
								@if($updateCount == $totalUpdateCount)
									<tr>
										<td colspan="6" class="alert alert-info mar-t-10"></td>
									</tr>
								@endif
							@endforeach
							</tbody>
						</table>
					@else
						<div class="text text-info text-bold font-24 text-center">
							<i class="glyphicon glyphicon-search"></i>
							No tickets were there, you can apply filters.
						</div>
					@endif
				</div>
			</div>
		</div>
	</div>
@endsection
@section('javascript')
	<script type="text/javascript">
		$(document).ready(function () {

			initPlugins();

			function initPlugins() {
				$('.filter-anlytics-creation-start-time, ' +
					'.filter-anlytics-creation-end-time').datetimepicker({
					timepicker: true,
					scrollInput: false,
					scrollMonth: false,
					closeOnDateSelect: false,
					format: "d-m-Y H:i",
					formatTime: "H:i",
				});
			}

			$('.btn-filter-by-cd').click(function (event) { // filter by party date
				event.preventDefault();
				var startDate = $('.filter-anlytics-creation-start-time').val();
				var endDate = $('.filter-anlytics-creation-end-time').val();
				var parts = startDate.split("-");
				var d1 = new Date(parts[2], parts[1] - 1, parts[0]);

				if (!startDate || !endDate) {
					showNotyError("Please select both start date & end date.")
				}
				else {
					var url = '';
					if (startDate) url = formUrl(url, 'filterChosenStartingTime', startDate, false, ['page']);
					if (endDate) url = formUrl(url, 'filterChosenEndingTime', endDate, false, ['page']);
					refreshUrl(url);
				}
			});

			var filterChosenStartingTime = $('#startTime').val();
			var filterChosenEndingTime = $('#endTime').val();

			function getQueryParams(a) {
				if (a == "") return {};
				var b = {};
				for (var i = 0; i < a.length; ++i) {
					var p = a[i].split('=');
					if (p.length != 2) continue;
					b[p[0]] = decodeURIComponent(p[1].replace(/\+/g, " "));
				}
				return b;
			}

			function formUrl(cUrl, key, value, isIgnore, ignores) {
				cUrl = cUrl ? cUrl.substr(cUrl.indexOf('?') + 1).split('&') : window.location.search.substr(1).split('&');
				var cParams = getQueryParams(cUrl), queryString = "", loc = window.location;
				var url = loc.protocol + '//' + loc.host + loc.pathname;
				if (isIgnore) { // remove from current object
					if (cParams.hasOwnProperty(key)) {
						try {
							delete cParams[key];
						}
						catch (e) {
						}
					}
				} else cParams[key] = value;
				for (key in cParams) { // form string
					if (ignores && ignores.constructor === Array && window.indexOf.call(ignores, key) >= 0) continue;
					queryString += key + "=" + cParams[key] + "&";
				}
				if (queryString) {
					url += '?' + queryString;
					url = url.slice(0, -1); // remove trailing '&'
				}
				return url;
			}

			function refreshUrl(url) {
				window.location.href = url;
			}

			function updateUrlByFilters(event) {
				event.preventDefault();

				var ticketStatusId = $('#ticketStatusId').val();
				var filterChosenStartingTime = $('#startTime').val();
				var filterChosenEndingTime = $('#endTime').val();
				var handlerId = $('#handlerId').val();
				var url = "history?";
				var isUrlChanged = false;

				if (filterChosenStartingTime) {
					isUrlChanged = true;
					url += '&filterChosenStartingTime=' + filterChosenStartingTime;
				}
				if (filterChosenEndingTime) {
					isUrlChanged = true;
					url += '&filterChosenEndingTime=' + filterChosenEndingTime;
				}
				if (ticketStatusId) {
					isUrlChanged = true;
					url += '&ticketStatusId=' + ticketStatusId;
				}
				if (handlerId) {
					isUrlChanged = true;
					url += '&handlerId=' + handlerId;
				}
				if (isUrlChanged) {
					location.href = url;
				}
			}

			$('#searchQuery').keyup(function (event) {
				if (event.which == 13 && $(this).val()) { // on enter submit search
					updateUrlByFilters(event);
				}
			});

			$('#ticketStatusId').change(updateUrlByFilters);
			$('#handlerId').change(updateUrlByFilters);
		});
	</script>

@endsection