routes/web.php
		Route::post('/', [
			'as'   => 'update',
			'uses' => 'UtilitiesController@updateSellingStatus'
		]);
	});

	/**
	 * Copy feature
	 */
	Route::group(['prefix' => 'copy', 'namespace' => 'Util'], function () {
		Route::get('/', [
			'as'   => 'show.copy.model',
			'uses' => 'CopyOptionController@showCopyModel'
		]);

		Route::post('/', [
			'as'   => 'copy.model.save',
			'uses' => 'CopyOptionController@saveCopyModel'
		]);
	});

	/*
	 * Tracking the order, call to customer, call to partner, customer feedback after party
	 */
	Route::group(['middleware' => 'authorize.tracking',
	              'prefix'     => 'tracking',
	              'as'         => 'tracking.'], function () {
		Route::group(['namespace' => 'Util'], function () {

			Route::get('pending/feedback', [
				'as'   => 'pending.feedback',
				'uses' => 'CustomerFeedbackController@showPendingFeedback'
			]);

			Route::get('pending/feedback/approval', [
				'as'   => 'pending.feedback.approval',
				'uses' => 'CustomerFeedbackController@showPendingApproval'
			]);
		});

		Route::group(['namespace' => 'Tracking'], function () {

			Route::get('/party/current', [
				'as'   => 'list',
				'uses' => 'TrackingController@showList'
			]);

			Route::get('/party/all/{done?}', [
				'as'   => 'party.all',
				'uses' => 'TrackingController@showList'
			]);

			Route::get('{bookingId}/{tracker_id}', [
				'as'   => 'show.model',
				'uses' => 'TrackingController@showModel'
			]);

			Route::post('details/save', [
				'as'   => 'save',
				'uses' => 'TrackingController@saveModel'
			]);

			Route::post('patner/unavailable', [
				'as'   => 'partner.unavailable',
				'uses' => 'TrackingController@sendPartnerUnavailableMail'
			]);
		});
	});

	/**
	 * Dash board based on each team.
	 */
	Route::group(['prefix'    => 'dash-board',
	              'as'        => 'dashBoard.',
	              'namespace' => 'DashBoard'], function () {
		Route::get('/', [
			'as'   => 'list',
			'uses' => 'DashBoardController@showList'
		]);
	});

	/**
	 * CRM Dash board based on ticket data.
	 */
	Route::group(['prefix'     => 'crm-analytics',
	              'as'         => 'crmDashBoard.',
	              'middleware' => 'authorize.old-dashboard',
	              'namespace'  => 'DashBoard'], function () {
		Route::get('/new-tickets', [
			'as'   => 'new.tickets.list',
			'uses' => 'CrmDashBoardController@showNewTickets'
		]);

		Route::get('/progress-tickets', [
			'as'   => 'progress.tickets.list',
			'uses' => 'CrmDashBoardController@showInProgressTickets'
		]);

		Route::get('/return-tickets', [
			'as'   => 'return.tickets.list',
			'uses' => 'CrmDashBoardController@showReturnTickets'
		]);

		Route::get('/missed-tickets', [
			'as'   => 'missed.tickets.list',
			'uses' => 'CrmDashBoardController@showMissedTickets'
		]);

		Route::get('/prospect-tickets', [
			'as'   => 'prospect.tickets.list',
			'uses' => 'CrmDashBoardController@showProspectTickets'
		]);

		Route::post('/return-tickets/{ticketId}', [
			'as'   => 'return.tickets.updates',
			'uses' => 'CrmDashBoardController@showReturnTicketUpdates'
		]);

		Route::post('/history/{ticketId}', [
			'as'   => 'history.tickets.updates',
			'uses' => 'CrmDashBoardController@showHistoryUpdates'
		]);

		Route::get('/avail-checks', [
			'as'   => 'avail-check.list',
			'uses' => 'CrmDashBoardController@showAvailChecks'
		]);

		Route::get('/metrics', [
			'as'   => 'metrics',
			'uses' => 'CrmDashBoardController@showMetrics'
		]);

		Route::get('/history', [
			'as'   => 'history',
			'uses' => 'CrmDashBoardController@showHistory'
		]);
	});
	/**
	 * ops-dashbaord based on ticket data
	 */
	Route::group(['prefix'    => 'ops-dashboard',
	              'as'        => 'ops-dashboard.',
	              'namespace' => 'DashBoard'], function () {
		Route::get('/', [
			'as'   => 'home',
			'uses' => 'OpsDashboardController@showOrderConfirmationTickets'
		]);

		Route::get('tabs-count', [
			'as'   => 'tabs-count',
			'uses' => 'OpsDashboardController@fetchTabsCount'
		]);

		Route::group(['prefix' => 'order-confirmation-tickets',
		              'as'     => 'order-confirmation-tickets.'], function () {
			Route::get('/', [
				'as'   => 'list',
				'uses' => 'OpsDashboardController@showOrderConfirmationTickets'
			]);

			Route::post('/confirm-partner/{id}', [
				'uses' => 'OpsDashboardController@confirmPartner'
			]);

			Route::get('search', [
				'as'   => 'search',
				'uses' => 'OpsDashboardController@searchOrderConfirmationsData'
			]);
		});

		Route::get('customer-updates', [
			'as'   => 'customer-updates.list',
			'uses' => 'OpsDashboardController@showCustomerUpdates'
		]);

		Route::get('order-tracking', [
			'as'   => 'order-tracking.list',
			'uses' => 'OpsDashboardController@showOrderTracking'
		]);

		Route::group(['prefix' => 'avail-checks',
		              'as'     => 'avail-checks.'], function () {
			Route::get('/', [
				'as'   => 'list',
				'uses' => 'OpsDashboardController@showAvailabilityChecks'
			]);

			Route::post('/get-details', [
				'as'   => 'details',
				'uses' => 'OpsDashboardController@fetchAvailabilityData'
			]);

			Route::post('/confirm-avail-check', [
				'as'   => 'sendCheck',
				'uses' => 'OpsDashboardController@confirmAvailCheck'
			]);
		});

		Route::group(['prefix' => 'customer-proofs',
		              'as'     => 'customer-proofs.'], function () {
			Route::get('/', [
				'as'   => 'list',
				'uses' => 'OpsDashboardController@showCustomerProofs'
			]);

			Route::get('search', [
				'as'   => 'search',
				'uses' => 'OpsDashboardController@searchCustomerProofsData'
			]);

			Route::post('validate', [
				'as'   => 'validate',
				'uses' => 'OpsDashboardController@validateCustomerProofs'
			]);
		});
		/**
		 * Customer Reviews in ops dashboard.
		 */

		Route::get('customer-reviews', [
			'as'   => 'customer-reviews.list',
			'uses' => 'OpsDashboardController@showCustomerReviews'
		]);
		Route::get('customer-reviews/resolve', [

			'uses' => 'OpsDashboardController@resolveCustomerReview'

		]);

		Route::group(['prefix' => 'option-availability',
		              'as'     => 'option-availability.'], function () {
			Route::get('/', [
				'as'   => 'info',
				'uses' => 'OpsDashboardController@showOptionAvailability'
			]);

			Route::get('option-slots', [
				'as'   => 'option-slots',
				'uses' => 'OpsDashboardController@fetchOptionSlots'
			]);

			Route::post('add-unavailability', [
				'as'   => 'add-unavailability',
				'uses' => 'OpsDashboardController@addUnavailability'
			]);
		});
	});

	/**
	 * PIAB-dashboard
	 *
	 */
	Route::group(['prefix' => 'piab-dashboard', 'as' => 'piab-dashboard.', 'namespace' => 'DashBoard'], function () {
		Route::group(['prefix' => 'product-bookings', 'as' => 'product-bookings.'], function () {
			Route::get('/', [
				'as'   => 'list',
				'uses' => 'PiabDashboardController@showProductBookings'
			]);
			Route::get('{id}/info', [
				'as'   => 'info',
				'uses' => 'PiabDashboardController@showProductBookingInfo'
			]);

			Route::post('update-status', [
				'uses' => 'PiabDashboardController@updateProductBookingStatus'
			]);

		});
	});

	/**
	 * Coupon consoles.
	 */
	Route::group(['prefix'    => 'coupon',
	              'as'        => 'coupon.',
	              'namespace' => 'Coupon'], function () {
		Route::get('/redeemed', [
			'as'   => 'redeemed',
			'uses' => 'CouponController@showRedeemed'
		]);

		Route::get('/available', [
			'as'   => 'available',
			'uses' => 'CouponController@showAvailableCoupons'
		]);

		Route::get('/trails', [
			'as'   => 'trails',
			'uses' => 'CouponController@showTrails'
		]);
	});

	Route::group(['prefix' => 'virtual-party', 'as' => 'virtual-party.', 'namespace' => 'Util'], function () {
		Route::get('/', [
			'as'   => 'home',
			'uses' => 'VirtualPartyController@getVirtualPartiesList'
		]);

		Route::get('{id}', [
			'as'   => 'details',
			'uses' => 'VirtualPartyController@getVirtualPartyDetails'
		]);

		Route::post('/', [
			'as'   => 'save',
			'uses' => 'VirtualPartyController@createVirtualParty'
		]);

		Route::post('{id}/update', [
			'as'   => 'update',
			'uses' => 'VirtualPartyController@updateVirtualParty'
		]);
	});

	/**
	 * Update tags - ADD/DELETE tags.
	 */
	Route::group(['prefix'    => 'revamp-tags',
	              'as'        => 'revamp.tags.',
	              'namespace' => 'Util'], function () {
		Route::get('/', [
			'as'   => 'list',
			'uses' => 'TagUpgradeController@showList'
		]);

		Route::post('/delete/{tagId?}/{decorId?}', [
			'as'   => 'delete.tag',
			'uses' => 'TagUpgradeController@deleteTag'
		]);

		Route::post('/add/{decorId}', [
			'as'   => 'add.tag',
			'uses' => 'TagUpgradeController@addTag'
		]);

		Route::post('/add/event/{decorId}', [
			'as'   => 'add.event',
			'uses' => 'TagUpgradeController@addEvent'
		]);

		Route::post('/delete/event/{eventId?}/{decorId?}', [
			'as'   => 'delete.event',
			'uses' => 'TagUpgradeController@deleteEvent'
		]);
	});

	/**
	 * New packages added in main will be displayed here.
	 */
	Route::group(['prefix'    => 'partner/add/new-package',
	              'as'        => 'partner.add.package.',
	              'namespace' => 'Partner'], function () {
		Route::get('/', [
			'as'   => 'list',
			'uses' => 'PartnerPackageController@showList'
		]);

		Route::get('/{packageId}', [
			'as'   => 'profile',
			'uses' => 'PartnerPackageController@showDetails'
		]);

		Route::get('/{packageId}/accept', [
			'as'   => 'accept.approval',
			'uses' => 'PartnerPackageController@acceptPackageApproval'
		]);

		Route::post('/{packageId}/reject', [
			'as'   => 'reject.approval',
			'uses' => 'PartnerPackageController@rejectPackageApproval'
		]);

		Route::post('/{packageId}/upgrade', [
			'as'   => 'upgrade',
			'uses' => 'PartnerPackageController@packageUpgrade'
		]);
	});

	/**
	 * Quick Book
	 *
	 * Shortcut method to quickly create booking and payment link for a ticket
	 */
	Route::group(['middleware' => 'authorize.quick-book',

app/Models/AvailCheck/AvailabilityCheck.php
<?php

namespace App\Models\AvailCheck;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class AvailabilityCheck extends Model
{
	use SoftDeletes;

	protected $table = 'availability_check';
}

app/Models/AvailCheck/AvailabilityCheckGallery.php
<?php

namespace App\Models\AvailCheck;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class AvailabilityCheckGallery extends Model
{
	use SoftDeletes;

	protected $table = 'availability_check_gallery';
}

app/Http/Controllers/AvailCheck/AvailCheckController.php
<?php

namespace App\Http\Controllers\AvailCheck;

use App\Http\Controllers\Base\BaseController;
use Illuminate\Support\Facades\Auth;

class AvailCheckController extends BaseController
{
	public function showInitialPage()
	{
		$user = Auth::user();
		$accessToken = $this->getAccessTokenFromUserId($user);

		$options = [
			"url"         => config("evibe.api.base_url") . config("evibe.api.avail-check.prefix") . "/initialize",
			"method"      => "POST",
			"accessToken" => $accessToken,
			"jsonData"    => []
		];

		$data = $this->makeGuzzleRequest($options);

		return view("availability.avail-check.initialize", ["data" => $data]);
	}

	public function showPartnerData($partnerTypeId, $partnerCode)
	{
		if ($partnerTypeId == config("evibe.ticket_type.venues") && (!(request("productId")) || (request("productId") == "")))
		{
			return redirect(route("avail.check.initialize"));
		}

		$user = Auth::user();
		$accessToken = $this->getAccessTokenFromUserId($user);

		$options = [
			"url"         => config("evibe.api.base_url") . config("evibe.api.avail-check.prefix") . "/" . $partnerTypeId . "/" . $partnerCode,
			"method"      => "POST",
			"accessToken" => $accessToken,
			"jsonData"    => [
				"productId" => request("productId")
			]
		];

		$data = $this->makeGuzzleRequest($options);

		return view("availability.avail-check.summary", ["data" => $data]);
	}

	public function showPartnerVenueData($partnerTypeId, $partnerCode)
	{
		$user = Auth::user();
		$accessToken = $this->getAccessTokenFromUserId($user);

		$options = [
			"url"         => config("evibe.api.base_url") . config("evibe.api.avail-check.prefix") . "/venue/" . $partnerTypeId . "/" . $partnerCode,
			"method"      => "POST",
			"accessToken" => $accessToken,
			"jsonData"    => []
		];

		$data = $this->makeGuzzleRequest($options);

		return $data;
	}

	public function savePartnerUnavailableSlot($partnerCode)
	{
		$user = Auth::user();
		$accessToken = $this->getAccessTokenFromUserId($user);

		$options = [
			"url"         => config("evibe.api.base_url") . config("evibe.api.avail-check.prefix") . "/add/" . $partnerCode,
			"method"      => "POST",
			"accessToken" => $accessToken,
			"jsonData"    => request()->all()
		];

		$data = $this->makeGuzzleRequest($options);

		return response()->json([
			                        "success" => isset($data["success"]) ? $data["success"] : false,
			                        "error"   => isset($data["error"]) ? $data["error"] : ""
		                        ]);
	}

	public function editPartnerUnavailableSlot($partnerCode)
	{
		$user = Auth::user();
		$accessToken = $this->getAccessTokenFromUserId($user);

		$options = [
			"url"         => config("evibe.api.base_url") . config("evibe.api.avail-check.prefix") . "/edit/" . $partnerCode,
			"method"      => "POST",
			"accessToken" => $accessToken,
			"jsonData"    => request()->all()
		];

		$data = $this->makeGuzzleRequest($options);

		return response()->json([
			                        "success" => isset($data["success"]) ? $data["success"] : false,
			                        "error"   => isset($data["error"]) ? $data["error"] : ""
		                        ]);
	}

	public function deletePartnerUnavailableSlot($partnerCode, $date, $slot)
	{
		$user = Auth::user();
		$accessToken = $this->getAccessTokenFromUserId($user);

		$options = [
			"url"         => config("evibe.api.base_url") . config("evibe.api.avail-check.prefix") . "/delete/" . $partnerCode,
			"method"      => "POST",
			"accessToken" => $accessToken,
			"jsonData"    => [
				"date"           => $date,
				"slot"           => $slot,
				"venuePackageId" => request("productId")
			]
		];

		$this->makeGuzzleRequest($options);

		return redirect()->back();
	}

	public function checkPartnerUnavailableSlot($partnerCode)
	{
		$user = Auth::user();
		$accessToken = $this->getAccessTokenFromUserId($user);

		$options = [
			"url"         => config("evibe.api.base_url") . config("evibe.api.avail-check.prefix") . "/check/" . $partnerCode,
			"method"      => "POST",
			"accessToken" => $accessToken,
			"jsonData"    => request()->all()
		];

		$data = $this->makeGuzzleRequest($options);

		return $data;
	}
}

resources/views/dashboard/ops/avail-checks/modals.blade.php
<div id="opsAvailCheckDetails" class="modal" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg">
		<div class="modal-content mar-t-10">
			<form id=" " action="" method="" enctype="multipart/form-data">
				<div class="modal-header">
					<h4 class="modal-title">Fill the details to ask availability check</h4>
				</div>
				<div class="modal-body">
					<div class="hide alert-danger pad-6 mar-b-15 " id="errorBox"></div>
					<div class="">
						<div class="col-sm-4 no-pad-l">
							<label class="no-pad"> Select partner </label>
						</div>

						<div class="col-sm-8 no-pad-l">
							<input type="text" name="availCheckPartners" id="availCheckPartners" class="form-control">
						</div>

						<ul id="availCheckPartnersData" class="hide">
							@foreach ($data['allPartners'] as $planner)
								<li data-id="{{ $planner['plannerId'] }}"
										data-name="{{ $planner['plannerName'] }}"
										data-person="{{ $planner['plannerPerson'] }}"
										data-code="{{ $planner['plannerCode'] }}"
										data-userid= "{{$planner['plannerUserId']}}">
								</li>
							@endforeach
						</ul>

						<ul id="venueData" class="hide"></ul>

						<div id="defaultId" data-id="0"></div>
						<div class="clearfix"></div>

						<div class="form-group mar-t-20">
							<div class="col-sm-4 no-pad-l">
								<label class="no-pad">Customer Name</label>
							</div>
							<div class="col-sm-8 no-pad-l">
								<input id="customerName" disabled class="form-control">
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="form-group mar-t-20">
							<div class="col-sm-4 no-pad-l no-pad-l">
								<label class="no-pad">Option</label>
							</div>
							<div class="col-sm-8 no-pad-l">
								<input id="option" disabled class="form-control">
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="form-group mar-t-20 hide">
							<div class="col-sm-4 no-pad-l no-pad-l">
								<label class="no-pad">Option Type</label>
							</div>
							<div class="col-sm-8 no-pad-l">
								<input id="optionType" disabled class="form-control">
							</div>
							<div class="clearfix"></div>
						</div>

						<div class="form-group mar-t-20">
							<div class="col-sm-4 no-pad-l no-pad-l">
								<label class="no-pad">Budget</label>
							</div>
							<div class="col-sm-8 no-pad-l">
								<input type="text" id="budget" class="form-control">
							</div>
							<div class="clearfix"></div>
						</div>


						<div class="form-group">
							<div class="col-sm-4 no-pad-l">
								<label>Party date time </label>
							</div>
							<div class="col-sm-8 no-pad-l">
								<input type="text" id="partyDateTime" class="form-control" disabled>
							</div>
							<div class="clearfix"></div>
						</div>

						<div class="form-group">
							<div class="col-sm-4 no-pad-l">
								<label> Inclusions </label>
							</div>
							<div class="col-sm-8 no-pad-l">
								<textarea class="form-control" rows="4" name="check-info" id="getCheckInfo" placeholder="Enter information" style="width: 100%;"></textarea>
							</div>
							<div class="clearfix"></div>
						</div>

						<div class="new-option-images hide">
							<div class="mar-t-10 mar-l-10">
								<label> Uploaded Images from Links/Pc </label>
							</div>
							<div class="panel panel-default" style="width: 100%">

								<div id="linkImages" class="link-images">
								</div>
								<div id="uploadedImages" class="mar-l-20 mar-b-10">

								</div>
							</div>
						</div>


						<div class="panel panel-default" style="width:100%;">
							<div class="mar-l-20 mar-t-10">
								<h4 class="modal-title"> Upload New Images<span
											class="font-13 text-info"> (Choose one way to upload the images)</span>
								</h4>
							</div>
							<hr>
							<div class="check-upload-type">
								<div class="text-black text-center mar-b-10 mar-t-10 ">
									<div class="col-sm-6">
										<label class="mar-r-10"><input type="radio" name="uploadType" value="1" checked> Upload From Link</label>
									</div>
									<div class="col-sm-6">
										<label class="mar-r-10"><input type="radio" name="uploadType" value="2"> Upload From Image</label>
									</div>
									<div class="clearfix"></div>
								</div>

								<div class="form-group pad-10 link-input">
									<div class="alert alert-info no-pad">
										<div class="mar-t-10 pad-t-10">
											<div class="no-pad text-center pad-r-3 pad-l-3" style="width: auto">
												<input type="url" id="uploadImageLink" placeholder="Enter valid image url" class="form-control image-links">
											</div>
											<div class="mar-t-10 text-center pad-b-10">
												<div class="btn btn-info btn-add-upload-link">
													<i class="glyphicon glyphicon-cloud-upload"></i> Add Image Link
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="form-group pad-10 hide pc-input">
									<div class="alert alert-info no-pad">
										<div class="form-group no-mar-b" id="imageCheck">
											<div class="gal-type-image">
												<div class="text-center pad-t-10 pad-b-10">
													<label for="files" class="btn btn-info">
														<i class="glyphicon glyphicon-cloud-upload"></i> Click To Add Images
													</label>
													<input type="file" id="files" accept="image/png, image/jpeg, image/jpg, image/JPG" class="hide" name="files[]" multiple/>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="option-images">
							<div class="mar-t-10 mar-l-10">
								<label> Existing Option Images(from CRM) </label>
							</div>
							<div class="panel panel-default" style="width: 100%">
								<div class="existing-images" id="imageLinks">

								</div>
							</div>
						</div>

					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-warning" id="btnBackPostAvailCheck" data-dismiss="modal"><i
									class="glyphicon glyphicon-remove"></i> Close
						</button>
						<button type="button" id="submitAvailCheck" class="btn btn-success" data-url="{{route("ops-dashboard.avail-checks.sendCheck")}}"><i
									class="glyphicon glyphicon-floppy-save"></i> Ask Avail Check
						</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>